In [6]:
import numpy as np

a = np.random.randn(5)

print(a)

[ 0.90718571  0.04388599 -0.80319373  1.8463361   0.32853631]


In [7]:
a.shape

(5,)

In [8]:
a.T

array([ 0.90718571,  0.04388599, -0.80319373,  1.8463361 ,  0.32853631])

In [9]:
np.dot(a,a.T)

4.986925145154799

## correct operations

In [10]:
a =np.random.rand(5,1)
a

array([[0.34706539],
       [0.41738012],
       [0.13598418],
       [0.4981945 ],
       [0.30180049]])

In [11]:
a.T

array([[0.34706539, 0.41738012, 0.13598418, 0.4981945 , 0.30180049]])

In [12]:
np.dot(a,a.T)

array([[0.12045439, 0.1448582 , 0.0471954 , 0.17290607, 0.1047445 ],
       [0.1448582 , 0.17420617, 0.05675709, 0.20793648, 0.12596552],
       [0.0471954 , 0.05675709, 0.0184917 , 0.06774657, 0.04104009],
       [0.17290607, 0.20793648, 0.06774657, 0.24819776, 0.15035534],
       [0.1047445 , 0.12596552, 0.04104009, 0.15035534, 0.09108353]])

### Normalizing rows

Another common technique we use in Machine Learning and Deep Learning is to normalize our data. It often leads to a better performance because gradient descent converges faster after normalization. Here, by normalization we mean changing x to $ \frac{x}{\| x\|} $ (dividing each row vector of x by its norm).

For example, if $$x = 
\begin{bmatrix}
    0 & 3 & 4 \\
    2 & 6 & 4 \\
\end{bmatrix}\tag{3}$$ then $$\| x\| = np.linalg.norm(x, axis = 1, keepdims = True) = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix}\tag{4} $$and        $$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}\tag{5}$$ Note that you can divide matrices of different sizes and it works fine: this is called broadcasting and you're going to learn about it in part 5.


**Exercise**: Implement normalizeRows() to normalize the rows of a matrix. After applying this function to an input matrix x, each row of x should be a vector of unit length (meaning length 1).